---
name: "Hello World"
description: "Greet someone"

inputs:
  python_version:
    required: true
    default: "3.11"

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}}
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Setup pipenv cache
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: "${{ runner.os }}-pipenv-${{ hashFiles('${{ github.workspace }}/Pipfile.lock') }}"
    - name: Setup
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: make install dev=true
