---
on:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      # - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.11"
      # - name: Install pipenv
      #   run: python -m pip install --upgrade pipenv wheel
      # - name: Setup pipenv cache
      #   id: cache-pipenv
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      # - name: Setup
      #   if: steps.cache-pipenv.outputs.cache-hit != 'true'
      #   run: make install dev=true
      # - name: Build
      #   run: make build
      # - name: Test
      #   run: make test
